openapi: 3.2.0
info:
  title: OpenAPI definition Tcf Disclosure Controller API
  version: v0
servers:
- url: https://services.amobee.com
  description: Generated server url
tags:
- name: tcf-disclosure-controller
paths:
  /files/TCFDisclosure.json:
    get:
      tags:
      - tcf-disclosure-controller
      operationId: getTCFDisclosure
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
  /files/TCFDisclosure:
    get:
      tags:
      - tcf-disclosure-controller
      operationId: getTCFDisclosure_1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
